name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir LoZN64
          cp *.lua *.toc *.ogg LoZN64/
          zip -r LoZN64.zip LoZN64

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: "${{ secrets.LOZN64 }}"
          project_id: "698360"
          game_endpoint: "wow"
          file_path: "LoZN64.zip"
          game_versions: "12.0.5"
          release_type: "release"
          display_name: "LoZN64 - ${{ github.event.head_commit.timestamp }}"
          changelog: "${{ github.event.head_commit.message }}"
          changelog_type: "markdown"